#docker run --rm --privileged -v "${PWD}":/config --device=/dev/ttyUSB0 -it ghcr.io/esphome/esphome run esphome.yaml


esphome:
  name: heatpump
  area: heizungskeller

esp8266:
  board: nodemcuv2

#from platformio.ini
#platform = espressif8266

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi: !include wifi.yaml

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Heatpump Fallback Hotspot"
    password: "Td6mth2TGTF6"

captive_portal:
    